<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="functionflow" nsURI="ecore://nasdanika.org/models/function-flow"
    nsPrefix="org.nasdanika.models.function-flow">
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//ArchitectureDescriptionElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errors" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//RelationshipSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier" eSuperTypes="#//FlowElement ../../org.nasdanika.models.architecture/model/architecture.ecore#//RelationshipSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber" eSuperTypes="#//Supplier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorHandler" eSuperTypes="#//FlowElement ../../org.nasdanika.models.architecture/model/architecture.ecore#//RelationshipSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//RelationshipTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer" eSuperTypes="#//FlowElement ../../org.nasdanika.models.architecture/model/architecture.ecore#//RelationshipTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//Consumer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//Node #//Supplier #//Consumer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//FlowElement ../../org.nasdanika.models.architecture/model/architecture.ecore#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetOutput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Output type"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorTransition" eSuperTypes="#//Transition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//FlowElement ../../org.nasdanika.models.architecture/model/architecture.ecore#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupplierFlow" eSuperTypes="#//Flow #//Supplier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConsumerFlow" eSuperTypes="#//Flow #//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionFlow" eSuperTypes="#//Function ../../org.nasdanika.models.architecture/model/architecture.ecore#//CompositeNode #//SupplierFlow #//ConsumerFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true" interface="true"
      eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceSupplier" eSuperTypes="#//Supplier #//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceConsumer" eSuperTypes="#//Consumer #//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceFunction" eSuperTypes="#//Function #//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceTransition" eSuperTypes="#//Transition #//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCall" eSuperTypes="#//Call #//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceErrorTransition" eSuperTypes="#//ErrorTransition #//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceErrorHandler" eSuperTypes="#//ErrorHandler #//Source"/>
</ecore:EPackage>
